export const AUDIO_INFORMATION_REQUEST = 'AUDIO_INFORMATION_REQUEST';
export const AUDIO_INFORMATION_SUCCESS = 'AUDIO_INFORMATION_SUCCESS';
export const AUDIO_INFORMATION_FAILURE = 'AUDIO_INFORMATION_FAILURE';

export const AUDIO_SHARE_INFORMATION_REQUEST = 'AUDIO_SHARE_INFORMATION_REQUEST';
export const AUDIO_SHARE_INFORMATION_SUCCESS = 'AUDIO_SHARE_INFORMATION_SUCCESS';
export const AUDIO_SHARE_INFORMATION_FAILURE = 'AUDIO_SHARE_INFORMATION_FAILURE';
