export const AUDIO_INFORMATION_REQUEST = 'AUDIO_INFORMATION_REQUEST';
export const AUDIO_INFORMATION_SUCCESS = 'AUDIO_INFORMATION_SUCCESS';
export const AUDIO_INFORMATION_FAILURE = 'AUDIO_INFORMATION_FAILURE';

export const AUDIO_SHARE_INFORMATION_REQUEST = 'AUDIO_SHARE_INFORMATION_REQUEST';
export const AUDIO_SHARE_INFORMATION_SUCCESS = 'AUDIO_SHARE_INFORMATION_SUCCESS';
export const AUDIO_SHARE_INFORMATION_FAILURE = 'AUDIO_SHARE_INFORMATION_FAILURE';

export const AUDIO_LIST_FETCH_REQUEST = 'AUDIO_LIST_FETCH_REQUEST';
export const AUDIO_LIST_FETCH_SUCCESS = 'AUDIO_LIST_FETCH_SUCCESS';
export const AUDIO_LIST_FETCH_FAILURE = 'AUDIO_LIST_FETCH_FAILURE';

export const AUDIO_INFORMATION_USED_LIST_REQUEST = 'AUDIO_INFORMATION_USED_LIST_REQUEST';
export const AUDIO_INFORMATION_USED_LIST_SUCCESS = 'AUDIO_INFORMATION_USED_LIST_SUCCESS';
export const AUDIO_INFORMATION_USED_LIST_FAILURE = 'AUDIO_INFORMATION_USED_LIST_FAILURE';

export const AUDIO_SET_TRUE_SECTION_LOOP = 'AUDIO_SET_TRUE_SECTION_LOOP';
export const AUDIO_SET_FALSE_SECTION_LOOP = 'AUDIO_SET_FALSE_SECTION_LOOP';
export const AUDIO_TOOGLE_SECTION_LOOP = 'AUDIO_TOOGLE_SECTION_LOOP';